-- Migration initiale du schéma de facturation
-- Version V1 - Création des tables principales

CREATE TABLE public.client_table (
                                     enterprise_id bigint NOT NULL,
                                     address character varying(255),
                                     code_postal integer NOT NULL,
                                     ice bigint NOT NULL,
                                     mail_address character varying(255),
                                     name_contact character varying(255),
                                     name_enterprise character varying(255),
                                     phone_number character varying(255),
                                     public_id uuid NOT NULL,
                                     ville character varying(255),
                                     CONSTRAINT client_table_pkey PRIMARY KEY (enterprise_id),
                                     CONSTRAINT ukcmkvn567ek1x8789wjlur8ui6 UNIQUE (public_id)
);

CREATE TABLE public.utilisateur (
                                    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                    email character varying(255),
                                    firstname character varying(255),
                                    lastname character varying(255),
                                    password character varying(255) NOT NULL,
                                    role character varying(255),
                                    username character varying(255)
);

CREATE TABLE public.invoice_table (
                                      id bigint PRIMARY KEY,
                                      amount double precision NOT NULL,
                                      cheque_number bigint,
                                      date_facture timestamp(6) without time zone,
                                      date_payment timestamp(6) without time zone,
                                      deposit double precision NOT NULL,
                                      destination character varying(255),
                                      due_date timestamp(6) without time zone,
                                      expected_date_time timestamp(6) without time zone,
                                      fees_disbursements double precision NOT NULL,
                                      invoice_status character varying(255),
                                      mode character varying(255),
                                      payment_method character varying(255),
                                      project_description character varying(255),
                                      remise_number bigint,
                                      tva double precision NOT NULL,
                                      client_id bigint,
                                      scheduled_invoice_id bigint,
                                      CONSTRAINT invoice_table_invoice_status_check CHECK (
                                          invoice_status IN ('Draft', 'Valid', 'Sent', 'Pending', 'Paid', 'Overdue')
                                          ),
                                      CONSTRAINT invoice_table_mode_check CHECK (
                                          mode IN ('MANUEL', 'SCHEDULED')
                                          ),
                                      CONSTRAINT invoice_table_payment_method_check CHECK (
                                          payment_method IN ('TRANSFER', 'CHEQUE', 'EXCHANGE', 'CASH')
                                          )
);

CREATE TABLE public.scheduled_invoice (
                                          id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                          active boolean NOT NULL,
                                          amount double precision NOT NULL,
                                          delai_en_jours integer NOT NULL,
                                          deposit double precision NOT NULL,
                                          destination character varying(255),
                                          fees_disbursements double precision NOT NULL,
                                          frequency character varying(255),
                                          last_generated timestamp(6) without time zone,
                                          mode character varying(255),
                                          project_description character varying(255),
                                          tva double precision NOT NULL,
                                          client_enterprise_id bigint NOT NULL,
                                          CONSTRAINT scheduled_invoice_frequency_check CHECK (
                                              frequency IN ('NONE', 'MINUTELY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY')
                                              ),
                                          CONSTRAINT scheduled_invoice_mode_check CHECK (
                                              mode IN ('MANUEL', 'SCHEDULED')
                                              )
);

-- Clés étrangères

ALTER TABLE public.invoice_table
    ADD CONSTRAINT fk_invoice_scheduled FOREIGN KEY (scheduled_invoice_id) REFERENCES public.scheduled_invoice(id);

ALTER TABLE public.invoice_table
    ADD CONSTRAINT fk_invoice_client FOREIGN KEY (client_id) REFERENCES public.client_table(enterprise_id);

ALTER TABLE public.scheduled_invoice
    ADD CONSTRAINT fk_scheduled_client FOREIGN KEY (client_enterprise_id) REFERENCES public.client_table(enterprise_id);
