# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - invoicing-app-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registryforinvoicing.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0cb42eec017e4e228fb599606e0104c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_892443f4f8014b68b033fe30ae12b33e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registryforinvoicing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cb42eec017e4e228fb599606e0104c5 }}/invoicing-app-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'invoicing-app-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0ac52d03c84a459b8e07a3226f08c51b }}
        images: 'registryforinvoicing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cb42eec017e4e228fb599606e0104c5 }}/invoicing-app-dev:${{ github.sha }}'